# Generated by Django 5.2.12 on 2026-05-04 20:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0011_attachment_metadata_alter_attachment_created_at'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity physically available at this branch', max_digits=12, verbose_name='On Hand')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='el_fouad_product_stocks', to='base.branch', verbose_name='Branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='el_fouad_branch_stocks', to='products.producttemplate', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Branch Product Stock',
                'verbose_name_plural': 'Branch Product Stocks',
                'ordering': ['branch', 'product'],
                'unique_together': {('branch', 'product')},
            },
        ),
    ]
