# Generated by Django 5.2.12 on 2026-05-05 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_fouad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlfouadAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('api_key', models.CharField(help_text='Api-Key header value for Alfouad API', max_length=255, verbose_name='API Key')),
                ('base_url', models.CharField(default='https://alfouadpharmacies-test.roayatec.com', max_length=255, verbose_name='Base URL')),
                ('enabled', models.BooleanField(default=True, help_text='Disable to pause all background syncs', verbose_name='Enabled')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=5, help_text='How often the stock sync Celery task runs', verbose_name='Sync Interval (minutes)')),
                ('chunk_size', models.PositiveIntegerField(default=500, help_text='Records processed per bulk_create / bulk_update call', verbose_name='Bulk Chunk Size')),
                ('last_stock_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Stock Sync')),
                ('last_locations_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Locations Sync')),
                ('stock_sync_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('failed', 'Failed')], default='idle', max_length=20, verbose_name='Stock Sync Status')),
                ('last_error', models.TextField(blank=True, default='', help_text='Most recent error from a failed sync', verbose_name='Last Error')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Alfouad API Config',
                'verbose_name_plural': 'Alfouad API Configs',
            },
        ),
    ]
