# Generated by Django 5.2.12 on 2026-07-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_fouad', '0003_remove_salesorderline_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alfouadapiconfig',
            name='base_url',
            field=models.CharField(default='https://alfouadpharmacies.roayatec.com', max_length=255, verbose_name='Base URL'),
        ),
    ]
